#ifndef PARAMETER_H
#define PARAMETER_H

#define FRAME_DELAY 50

#define CANVAS_WIDTH 800
#define CANVAS_HEIGHT 600

#define STAIR_GENERATE_PERIOD 12
#define STAIR_RISING_SPEED 10
#define STAIR_WIDTH 200
#define STAIR_HEIGHT 20

#define LEFT_ROLL_STAIR_SPEED 10
#define RIGHT_ROLL_STAIR_SPEED 10

#define PLAYER_START_POSITION_X 400
#define PLAYER_START_POSITION_Y 10

#define PLAYER_WIDTH 50
#define PLAYER_HEIGHT 50

#define PLAYER_FALLING_SPEED 2
#define PLAYER_FALLING_ACCELERATION 1
#define PLAYER_MOVING_SPEED 30

#define DEFAULT_HEALTH 12

#define UPPER_SPIKE_DAMAGE 5
#define UPPER_SPIKE_HEIGHT 20

enum ITEM_ORDER {
    PLAYER_ITEM_ORDER,
    STAIR_ITEM_ORDER,
    UPPER_SPIKE_ITEM_ORDER,
    TEXT_ITEM_ORDER
};

#endif // PARAMETER_H
