#ifndef PARAMETER_H
#define PARAMETER_H

#define CANVAS_WIDTH 800
#define CANVAS_HEIGHT 600

#define STAIR_RISING_SPEED 5
#define STAIR_WIDTH 200
#define STAIR_HEIGHT 20

#define PLAYER_START_POSITION_X 400
#define PLAYER_START_POSITION_Y 10

#define PLAYER_WIDTH 50
#define PLAYER_HEIGHT 50

#define PLAYER_FALLING_SPEED 2
#define PLAYER_FALLING_ACCELERATION 1
#define PLAYER_MOVING_SPEED 30

#define DEFAUTL_HEALTH 12
#define UPPER_SPIKE_DAMAGE 5

#endif // PARAMETER_H
